---
title: Singapore Population Trends
author: ''
date: '2021-05-17'
slug: singapore-population-trends
categories:
  - DataViz
  - Tableau
tags: ['Tableau']
subtitle: ''
summary: ''
authors: [Ling Huang]
lastmod: '2021-05-17T20:55:29+08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


Population aging is a well-known phenomenon for many years in Singapore. But how does it affect the labor force market?

Recently, I gathered the Residents labor force data (from 2009 to 2019) from Singapore Ministry of Manpower website. In this post, I wanted to share some of the insights derived from my data visualization. In my data visualization, I compared the residents Labor Force Participation Rate in 2009 with that in 2019. Besides, I compared the Shares of different Age Groups in the labor market in 2009 and in 2019. The tool I used is Tableau.


# 1. Objective

Singapore Ministry of Manpower released the report [Labour Force in Singapore 2019](https://stats.mom.gov.sg/Pages/Labour-Force-In-Singapore-2019.aspx) on 30-Jan-2020. On the page #22, it threw a statement that **'More older residents in labor force'** and then illustrated it with the chart **'Residents Labor Force by Age'**.



